name: win-ssh-web

on:
  push:
    branches:
      - master

jobs:
  build-test-publish-ftp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.100'

      - name: Publish
        run: dotnet publish src/Presentation/Web/Web.csproj -c Release -o publish
      - name: Deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 2222
          source: publish/*
          target: '/c/inetpub/wwwroot/aspnetcorespa/'
          tar_dereference: true
          strip_components: 1
          rm: true